color_app/urls.py
from django.urls import path
from color_app import views


app_name = "color_app"
urlpatterns = [
    path('', views.home_view, name="index"),
    path('random/', views.random_color_view, name="random_color"),
    path('colors/', views.ColorListView.as_view(), name="color_list"),
    path('new_color/', views.NewColorView.as_view(), name="new_color")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('color_app.urls')),
    path('admin/', admin.site.urls),
    
]

color_app/models.py
from django.db import models
from django.urls import reverse
from colorsys import rgb_to_hsv, hsv_to_rgb
from color_app.validators import color_channel_validator

class Color(models.Model):
    name = models.CharField(max_length=50)
    red = models.IntegerField(validators=[color_channel_validator])
    green = models.IntegerField(validators=[color_channel_validator])
    blue = models.IntegerField(validators=[color_channel_validator])

    def hex_code(self):
        """Returns a hex representation of the color like #00ff00 (green) suitable for CSS.
        """
        return '#' + ''.join([self.int2hex(self.red), self.int2hex(self.green), self.int2hex(self.blue)])

    def int2hex(self, int_value):
        "Converts an integer value like 15 to a two-digit hex string like 0b"
        return hex(int_value)[2:].zfill(2)

    def inverted(self, name=None):
        """Returns a new color which is the 'opposite' of this one. 
        A color is defined by red, green, and blue values, each ranging from
        0-255. If a color's red, green, and blue values are (x, y, z), the 
        opposite color's values are (255-x, 255-y, 255-z). For example, white is 
        (255, 255, 255), so its opposite, black, is (0, 0, 0). 
        """
        if name is None:
            name = self.name + ' inverted'
        return Color(name=name, red=255-self.red, green=255-self.green, blue=255-self.blue)

    def to_hsv(self):
        "Returns the color as hue, saturation, value instead of in rgb"
        return rgb_to_hsv(self.red/255, self.green/255, self.blue/255)

    def adjust_hue(self, delta, name=''):
        "Adjust the hue of the color by `delta`."
        h, s, v  = self.to_hsv()
        r, g, b = hsv_to_rgb(h + delta % 1, s, v)
        return Color(name=name, red=int(r*255), green=int(g*255), blue=int(b*255))

    def adjust_saturation(self, delta, name=''):
        "Adjust the saturation of the color by `delta`."
        h, s, v  = self.to_hsv()
        r, g, b = hsv_to_rgb(h, clamp(s + delta, 0, 1), v)
        return Color(name=name, red=int(r*255), green=int(g*255), blue=int(b*255))

    def adjust_value(self, delta, name=''):
        "Adjust the value of the color by `delta`."
        h, s, v  = self.to_hsv()
        r, g, b = hsv_to_rgb(h, s, clamp(v + delta, 0, 1))
        return Color(name=name, red=int(r*255), green=int(g*255), blue=int(b*255))

    def get_absolute_url(self):
        "Returns a url to this model"
        return reverse("colors_app:color_detail", args=[self.id])

    def __str__(self):
        "Defines how a Color will be represented as a string"
        return "<Color {} ({}, {}, {})>".format(self.name, self.red, self.green, self.blue)

    def __repr__(self):
        "Defines how a Color will be represented in code"
        return str(self)

def clamp(value, low, high):
    "Ensures that the value is between low and high"
    return min(max(low, value), high)

color_app/forms.py
from django.forms import ModelForm
from color_app.widgets import ColorChannelRangeInput
from color_app.models import Color
from random import randint

class ColorForm(ModelForm):
    class Meta:
        model = Color
        fields = ['name', 'red', 'green', 'blue']
        widgets = {
            'red': ColorChannelRangeInput(),
            'green': ColorChannelRangeInput(),
            'blue': ColorChannelRangeInput(),
        }

color_app/views.py
from django.shortcuts import render
from color_app.models import Color
from random import randint
from django.views.generic import DetailView, ListView, CreateView
from django.urls import reverse_lazy
from color_app.models import Color
from color_app.forms import ColorForm

#######################
# Function Based Views
#######################


def home_view(request):
    "A view function which renders the homepage"

    skyblue = Color(name="skyblue", red=135, green=206, blue=250)

    params = {
        "name": "mufinized",
        "color": skyblue,
    }
    
    response = render(request, 'color_app/index.html', params)
    return response

def random_color_view(request):
    "A view function which renders a random color"

    random_color = Color(
        name="random color", 
        red=randint(0, 256), 
        green=randint(0, 256),
        blue=randint(0, 256)
    )

    params = {"color": random_color, "name": "mufinized"}

    return render(request, 'color_app/index.html', params)


def color_list(request):
    "A view function which renders a random color"



    return render(request, 'color_app/color_list.html', {})


#######################
# Class Based Views
#######################

class ColorListView(ListView):
    model = Color
    template_name = "color_app/color_list.html"
    queryset = Color.objects.order_by(*["red", "blue", "green"]).reverse()

class NewColorView(CreateView):
    model = Color
    form_class = ColorForm
    template_name = "color_app/color_form.html"
    success_url = reverse_lazy("color_app:color_list")

color_app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">

<head>
{% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    

    <!-- Custom CSS -->
    <link rel="stylesheet" type ="text/css" href="{% static 'color_app/style.css' %}">
    
    <link rel="icon" href="{% static "color_app/favicon.png" %}">
    <title>COLORAMA</title>
{% endblock %}
</head>
<body class="d-flex flex-column h-100">
  <header>
    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-brand">
          <span class="site-name"><a href="{% url 'color_app:index' %}">Colorama</a></span>
        </div>
      </div>
    </nav>
  </header>
  <main class="flex-shrink-0">
    <div id="main" class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</main>
<footer class="footer mt-auto">
  <div class="container-fluid">
    <span class="site-slogan">Your favorite color picker</span>
  </div>
</footer>


<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

color_app/templates/color_app/color_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col text-center">
      <h1>Add a new color</h1>
			<form method="post">
				{% csrf_token %}
    	  {{ form | crispy }}
				<input type="submit" value="Submit">
			</form>
			{% include "color_app/swatch.html" %}
    </div>
	  <script>
			const redSlider = document.getElementById('id_red')
			const greenSlider = document.getElementById('id_green')
			const blueSlider = document.getElementById('id_blue')
			const swatch = document.getElementsByTagName('circle')[0]
			const body = document.getElementsByTagName('body')[0]
			function hex(num) {
				const hexnum = parseInt(num).toString(16)
				return (hexnum.length == 2) ? hexnum : "0" + hexnum
		  }
		  function cssColor(red, green, blue) {
				return '#' + hex(red) + hex(green) + hex(blue)
			}
			function updateSwatch() {
				const swatchColor = cssColor(redSlider.value, greenSlider.value, blueSlider.value)
				const bgColor = cssColor(255 - redSlider.value, 255 - greenSlider.value, 255 - blueSlider.value)
				swatch.style['fill'] = swatchColor
				body.style['background-color'] = bgColor
				body.style['color'] = swatchColor
			}
			redSlider.addEventListener('input', updateSwatch)
			greenSlider.addEventListener('input', updateSwatch)
			blueSlider.addEventListener('input', updateSwatch)
			updateSwatch()
	  </script>
  </div>

{% endblock %}

color_app/templates/color_app/color_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col text-center">
      <h1>All the colors</h1>
      <p>
        <a href="{% url 'color_app:new_color' %}">
			    Add a new color
	      </a> 
      </p>
		</div>
	</div>
	<div class="swatches">
		<div class="swatch">
      <a href="{% url 'color_app:new_color' %}">
			  <svg width="200" height="200">
			    <circle cx="100" cy="100" r="80" style="stroke-width: 4px; stroke: black; fill: none;"></circle>
				  <text x="100" y="100" text-anchor="middle" style="dominant-baseline: central; font-size: 40px;">+</text>
			  </svg>
	    </a> 
		</div>
	  {% for color in object_list %}
		  <div class="swatch">
				{% include "color_app/swatch.html" %}
		  </div>
		{% endfor %}
	</div>
	<script src="{% static 'color_app/offset_swatches.js' %}"></script>
{% endblock %}

color_app/templates/color_app/index.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col text-center">
      <h1> Hello {{name}}</h1>
      {% include "color_app/swatch.html" %}
      <p>
        <a href="{% url 'color_app:random_color' %}">
	  How about a random color?
	</a> 
      </p>
    </div>
  </div>
{% endblock %}

color_app/templates/color_app/random_color.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  {{ block.super }}
  <title>COLORAMA</title>
  <style>
    body {
      background-color: {{color.inverted.hex_code}};
    }
    a {
      color: {{color.hex_code}};
    }
  </style>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col text-center">
      <h1>Random color</h1>
			<p>
			  Do you like it? If not, 
				<a href="{% url 'color_app:random_color' %}">choose another</a>.
			</p>
      {% include "color_app/swatch.html" %}
    </div>
  </div>
{% endblock %}

color_app/templates/color_app/swatch.html
<svg width="200" height="200">
	<circle cx="100" cy="100" r="84" style="stroke-width: 4px; stroke: black; fill:{{color.hex_code}}"></circle>
	<text x="100" y="100" text-anchor="middle" style="dominant-baseline: central;">{{color.name}}</text>
</svg>